
import { ArrowLeft, FileText, Terminal, Copy } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useNavigate } from 'react-router-dom';

const TxtPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-8">
          <Button variant="ghost" className="mb-4" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Previous Page
          </Button>
          
          <div className="flex items-center gap-4 mb-6">
            <div className="w-16 h-16 rounded-lg bg-gray-400 flex items-center justify-center">
              <span className="text-white font-bold text-sm">.txt</span>
            </div>
            <div>
              <h1 className="text-3xl font-bold text-foreground">Program Output Files</h1>
              <p className="text-muted-foreground">Console output and execution results</p>
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Terminal className="h-5 w-5" />
                About Output Files
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground">
                Text output files capture all console output generated by your program during execution. 
                This includes print statements, error messages, and any other text your program produces.
              </p>
              
              <div className="space-y-3">
                <h4 className="font-semibold">What's Included:</h4>
                <ul className="list-disc list-inside space-y-2 text-muted-foreground">
                  <li>Standard output (stdout) from your program</li>
                  <li>Standard error (stderr) messages</li>
                  <li>Debug information and trace statements</li>
                  <li>Test case execution results</li>
                  <li>Runtime warnings and notifications</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                File Structure
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold leading-none">1</div>
                  <div>
                    <h5 className="font-semibold">Execution Header</h5>
                    <p className="text-sm text-muted-foreground">Timestamp and environment information</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold leading-none">2</div>
                  <div>
                    <h5 className="font-semibold">Program Output</h5>
                    <p className="text-sm text-muted-foreground">Raw output from your program execution</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold leading-none">3</div>
                  <div>
                    <h5 className="font-semibold">Test Results</h5>
                    <p className="text-sm text-muted-foreground">Output comparison with expected results</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold leading-none">4</div>
                  <div>
                    <h5 className="font-semibold">Execution Summary</h5>
                    <p className="text-sm text-muted-foreground">Final status and performance metrics</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Example Code (OutPut File for sorter.cpp)
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-muted/50 rounded-lg p-4 overflow-x-auto">
                <pre className="text-sm">
                  <code>{`Build-dir:https://minio.xlabub.com/rai-ub/userdata/build-6830e1adcf814be242adff3f.tar.gz
src-dir:https://minio.xlabub.com/rai-ub/userdata/src-6830e1adcf814be242adff3f.tar.gz
output.log0000644000000000000000000000127515014160664011317 0ustar0000000000000000

Oracle has judged student answer
Graded at: 2025-05-23 16:59:32 US/Eastern (approx)
Grading Method:
1. The oracle program sent a series of prompts to the student program.
2. The student program responded to each prompt.
3. Each response was compared to the oracle's expected output.
4. Correctness score was calculated based on matching outputs.
5. Query score (if applicable) was calculated based on the quality or structure of responses.
6. Once all checks were complete, the oracle printed 'AUTOGRADER_COMPLETE' followed by the final result JSON.

{"scores": {"correctness": 100, "query_score": 79.399483}, "queries": 87, "correct_answer": "5 2 0 9 6 8 3 1 4 7 ", "array": "2 7 1 6 8 0 4 9 5 3 "}`}</code>
                </pre>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Copy className="h-5 w-5" />
                Usage Tips
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Badge variant="secondary">Debugging</Badge>
                    <p className="text-sm text-muted-foreground">Use output files to debug runtime issues</p>
                  </div>
                  
                  <div className="space-y-2">
                    <Badge variant="secondary">Verification</Badge>
                    <p className="text-sm text-muted-foreground">Verify your program produces correct output</p>
                  </div>
                  
                  <div className="space-y-2">
                    <Badge variant="secondary">Performance</Badge>
                    <p className="text-sm text-muted-foreground">Check execution time and resource usage</p>
                  </div>
                  
                  <div className="space-y-2">
                    <Badge variant="secondary">Comparison</Badge>
                    <p className="text-sm text-muted-foreground">Compare against expected test outputs</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default TxtPage;